services:
  webapp:
    build: .
    ports:
      - 8080:8080
    working_dir: /app
    stdin_open: true
    tty: true
    command: yarn serve
    volumes:
      - .:/app
      - node_modules:/app/node_modules


volumes:
  node_modules:
